# Generated by Django 3.1.6 on 2021-03-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('etatSujet', models.CharField(choices=[('PROPOSE', 'PROPOSE'), ('ACCORDE', 'ACCORDE'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SOUTENU', 'SOUTENU'), ('DEPOSE', 'DEPOSE')], default='PROPOSE', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
