# Generated by Django 3.1.6 on 2021-04-16 17:40

from django.db import migrations, models
import django.db.models.deletion
import sujet_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('etatSujet', models.CharField(choices=[('PROPOSE', 'PROPOSE'), ('ACCORDE', 'ACCORDE'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SOUTENU', 'SOUTENU'), ('DEPOSE', 'DEPOSE')], default='PROPOSE', max_length=10)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesSujets', to='administration.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='SujetValider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateValider', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujet')),
            ],
            options={
                'unique_together': {('sujet', 'personnel')},
            },
        ),
        migrations.CreateModel(
            name='SujetPostuler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePostuler', models.DateTimeField(auto_now_add=True)),
                ('motivation', models.TextField()),
                ('file_cv', models.FileField(blank=True, null=True, upload_to=sujet_module.models.upload_path)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujet')),
            ],
            options={
                'unique_together': {('personnel', 'sujet')},
            },
        ),
        migrations.CreateModel(
            name='SujetAccorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAccorde', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujet')),
            ],
            options={
                'unique_together': {('sujet', 'personnel')},
            },
        ),
        migrations.AddField(
            model_name='sujet',
            name='personnelAccorder',
            field=models.ManyToManyField(related_name='sujetsAccorder', through='sujet_module.SujetAccorder', to='administration.Personnel'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='personnelPostuler',
            field=models.ManyToManyField(related_name='sujetsPostuler', through='sujet_module.SujetPostuler', to='administration.Personnel'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='personnelValider',
            field=models.ManyToManyField(through='sujet_module.SujetValider', to='administration.Personnel'),
        ),
    ]
