# Generated by Django 3.1.6 on 2021-03-22 14:32

from django.db import migrations, models
import sujet_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('etatSujet', models.CharField(choices=[(sujet_module.models.EtatSujetEnumeration['ACCORDE'], 'ACCORDE'), (sujet_module.models.EtatSujetEnumeration['VALIDE'], 'VALIDE'), (sujet_module.models.EtatSujetEnumeration['TERMINE'], 'TERMINE'), (sujet_module.models.EtatSujetEnumeration['SOUTENU'], 'SOUTENU'), (sujet_module.models.EtatSujetEnumeration['DEPOSE'], 'DEPOSE')], default='PROPOSE', max_length=10)),
            ],
        ),
    ]
