# Generated by Django 3.1.6 on 2021-03-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('sujet_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sujetaccorde',
            unique_together={('enseignant', 'sujet', 'etudiant'), ('sujet', 'etudiant'), ('enseignant', 'sujet')},
        ),
    ]
