# Generated by Django 3.1.6 on 2021-03-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210331_1215'),
        ('sujet_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetAccorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAccorde', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujetsAccorde', to='administration.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='SujetPostuler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePostuler', models.DateTimeField(auto_now_add=True)),
                ('motivation', models.TextField()),
                ('cv', models.CharField(max_length=255)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujetsPostule', to='administration.personnel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='etudiantpostuler',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='etudiantpostuler',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='etudiantpostuler',
            name='sujet',
        ),
        migrations.AlterUniqueTogether(
            name='sujetaccorde',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sujetaccorde',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='sujetaccorde',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='sujetaccorde',
            name='sujet',
        ),
        migrations.AlterUniqueTogether(
            name='sujetvalide',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sujetvalide',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='sujetvalide',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='sujetvalide',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='EnseignantAccorde',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='EnseignantPostulant',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='EnseignantValide',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='postulants',
        ),
        migrations.DeleteModel(
            name='EnseignantPostuler',
        ),
        migrations.DeleteModel(
            name='EtudiantPostuler',
        ),
        migrations.DeleteModel(
            name='SujetAccorde',
        ),
        migrations.DeleteModel(
            name='SujetValide',
        ),
        migrations.AddField(
            model_name='sujetpostuler',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnesPostulant', to='sujet_module.sujet'),
        ),
        migrations.AddField(
            model_name='sujetaccorder',
            name='sujetPostuler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnesAccorde', to='sujet_module.sujetpostuler'),
        ),
        migrations.AlterUniqueTogether(
            name='sujetpostuler',
            unique_together={('personnel', 'sujet')},
        ),
        migrations.AlterUniqueTogether(
            name='sujetaccorder',
            unique_together={('sujetPostuler', 'personnel')},
        ),
    ]
