# Generated by Django 3.1.6 on 2021-03-22 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sujet_module.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sujet_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sujet',
            name='etatSujet',
            field=models.CharField(choices=[('PROPOSE', 'PROPOSE'), ('ACCORDE', 'ACCORDE'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SOUTENU', 'SOUTENU'), ('DEPOSE', 'DEPOSE')], default=sujet_module.models.EtatSujetEnumeration['PROPOSE'], max_length=10),
        ),
    ]
