# Generated by Django 3.1.6 on 2021-03-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('sujet_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantPostuler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePostuler', models.DateTimeField(auto_now_add=True)),
                ('motivation', models.TextField()),
                ('cv', models.CharField(max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujetsPostuler', to='administration.etudiant')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiantsPostuler', to='sujet_module.sujet')),
            ],
        ),
    ]
