# Generated by Django 3.1.6 on 2021-03-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('sujet_module', '0002_etudiantpostuler'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='postulants',
            field=models.ManyToManyField(related_name='sujets', through='sujet_module.EtudiantPostuler', to='administration.Etudiant'),
        ),
        migrations.AlterField(
            model_name='etudiantpostuler',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etudiant'),
        ),
        migrations.AlterField(
            model_name='etudiantpostuler',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujet'),
        ),
    ]
