# Generated by Django 3.1.6 on 2021-03-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20210331_1907'),
        ('sujet_module', '0003_auto_20210331_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujetpostuler',
            name='personnesAccorde',
            field=models.ManyToManyField(related_name='sujetsAccorde', through='sujet_module.SujetAccorder', to='administration.Personnel'),
        ),
        migrations.AlterField(
            model_name='sujetaccorder',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel'),
        ),
        migrations.AlterField(
            model_name='sujetaccorder',
            name='sujetPostuler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujetpostuler'),
        ),
    ]
