# Generated by Django 3.1.6 on 2021-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('sujet_module', '0003_auto_20210324_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='postulants',
            field=models.ManyToManyField(related_name='sujetsPostuler', through='sujet_module.EtudiantPostuler', to='administration.Etudiant'),
        ),
    ]
