# Generated by Django 3.1.6 on 2021-03-31 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20210331_1907'),
        ('sujet_module', '0004_auto_20210331_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='owner',
        ),
        migrations.AddField(
            model_name='sujet',
            name='personnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mesSujets', to='administration.personnel'),
            preserve_default=False,
        ),
    ]
