# Generated by Django 3.1.6 on 2021-03-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('sujet_module', '0004_auto_20210324_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantPostuler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePostuler', models.DateTimeField(auto_now_add=True)),
                ('motivatin', models.TextField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.enseignent')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujet')),
            ],
        ),
        migrations.AddField(
            model_name='sujet',
            name='EnseignantPostulant',
            field=models.ManyToManyField(related_name='sujetsPostuler', through='sujet_module.EnseignantPostuler', to='administration.Enseignent'),
        ),
    ]
