# Generated by Django 3.1.6 on 2021-03-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('sujet_module', '0005_auto_20210324_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enseignantpostuler',
            unique_together={('enseignant', 'sujet')},
        ),
        migrations.AlterUniqueTogether(
            name='etudiantpostuler',
            unique_together={('etudiant', 'sujet')},
        ),
    ]
