# Generated by Django 3.1.6 on 2021-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20210331_1907'),
        ('sujet_module', '0005_auto_20210331_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetpostuler',
            name='personnesAccorde',
            field=models.ManyToManyField(related_name='sujetsAccorder', through='sujet_module.SujetAccorder', to='administration.Personnel'),
        ),
    ]
