# Generated by Django 3.1.6 on 2021-03-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sujet_module', '0006_auto_20210324_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignantpostuler',
            old_name='motivatin',
            new_name='motivation',
        ),
    ]
