# Generated by Django 3.1.6 on 2021-04-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20210331_1907'),
        ('sujet_module', '0006_auto_20210331_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujet',
            old_name='personnesPostulant',
            new_name='personnelPostuler',
        ),
        migrations.RemoveField(
            model_name='sujetpostuler',
            name='personnesAccorde',
        ),
        migrations.AddField(
            model_name='sujet',
            name='personnelAccorder',
            field=models.ManyToManyField(related_name='sujetsAccorder', through='sujet_module.SujetAccorder', to='administration.Personnel'),
        ),
        migrations.AddField(
            model_name='sujetaccorder',
            name='sujet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sujet_module.sujet'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sujetaccorder',
            unique_together={('sujet', 'personnel')},
        ),
        migrations.RemoveField(
            model_name='sujetaccorder',
            name='sujetPostuler',
        ),
    ]
