# Generated by Django 3.1.6 on 2021-04-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sujet_module', '0008_auto_20210410_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujetaccorder',
            name='valide',
        ),
    ]
