# Generated by Django 3.1.6 on 2021-02-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('anneScolaire', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='2021', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=100)),
                ('departemeant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='administration.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('L3', 'licence 3'), ('M2', 'Master 2'), ('T1', 'These 1'), ('T2', 'These 2'), ('T3', 'These 3')], default='M2', max_length=2)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='administration.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ine', models.CharField(max_length=7)),
                ('classe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='administration.classe')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='administration.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cni', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('departemeant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='administration.departement')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='administration.specialite'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('anneScolaire', 'specialite')},
        ),
    ]
