# Generated by Django 3.1.6 on 2021-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='profil',
            field=models.CharField(choices=[('ETUDIANT', 'ETUDIANT'), ('ENSEIGNANT', 'ENSEIGNANT'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('cni',)},
        ),
    ]
