# Generated by Django 3.1.6 on 2021-02-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='anneScolaire',
            new_name='anneeScolaire',
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('anneeScolaire', 'specialite')},
        ),
    ]
