# Generated by Django 3.1.6 on 2021-02-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210204_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiere',
            old_name='departemeant',
            new_name='departement',
        ),
    ]
