# Generated by Django 3.1.6 on 2021-02-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210204_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignent',
            old_name='departemeant',
            new_name='departement',
        ),
    ]
