# Generated by Django 3.1.6 on 2021-03-31 13:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0004_auto_20210331_1338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enseignent',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='etudiant',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personnel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.AddField(
            model_name='personnel',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
