# Generated by Django 3.1.6 on 2021-02-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210204_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephon',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
