# Generated by Django 3.1.6 on 2021-03-31 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0005_auto_20210331_1341'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enseignent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='etudiant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personnel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
    ]
