# Generated by Django 3.1.6 on 2021-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20210217_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignent',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='enseignent',
            name='telephon',
            field=models.CharField(default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
