# Generated by Django 3.1.6 on 2021-03-31 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0006_auto_20210331_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('user',), ('cni',)},
        ),
    ]
