# Generated by Django 3.1.6 on 2021-02-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20210218_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='niveau',
            field=models.CharField(choices=[('BTS', 'BTS'), ('L3', 'licence 3'), ('M2', 'Master 2'), ('T1', 'These 1'), ('T2', 'These 2'), ('T3', 'These 3')], default='M2', max_length=10),
        ),
    ]
