# Generated by Django 3.1.6 on 2021-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20210218_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
