# Generated by Django 3.1.6 on 2021-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20210414_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='sujet_valide',
        ),
        migrations.AddField(
            model_name='personnel',
            name='nbr_sujet_valide',
            field=models.IntegerField(default=0),
        ),
    ]
