# Generated by Django 3.1.6 on 2021-04-27 17:48

from django.db import migrations, models
import django.db.models.deletion
import encadrement.models


class Migration(migrations.Migration):

    dependencies = [
        ('encadrement', '0002_auto_20210427_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=encadrement.models.upload_path)),
                ('encadrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='encadrement.encadrement')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('duree', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateEvenement', models.DateTimeField()),
                ('encadrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='encadrement.encadrement')),
            ],
        ),
    ]
