# Generated by Django 3.1.6 on 2021-04-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('encadrement', '0004_encadrement_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrement',
            name='owner',
        ),
        migrations.AddField(
            model_name='evenement',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='administration.personnel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ressource',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='administration.personnel'),
            preserve_default=False,
        ),
    ]
